import { createHash } from "node:crypto";
import type { PatchFileCoverage } from "../analyzers/patch-analyzer.js";
import type { CommentFilesMode } from "../types/config.js";
import type { AggregatedCoverageResults } from "../types/coverage.js";
import type {
  AggregatedTestResults,
  TestComparison,
} from "../types/test-results.js";

export interface GitHubContext {
  owner: string;
  repo: string;
  prNumber: number;
  serverUrl: string;
}

export interface ReportFormatOptions {
  filesMode?: CommentFilesMode;
  changedFiles?: string[];
  patchTarget?: number;
  patchFileBreakdown?: PatchFileCoverage[];
  githubContext?: GitHubContext;
}

export class ReportFormatter {
  /**
   * Format test results and coverage as a markdown report
   */
  formatReport(
    testResults?: AggregatedTestResults,
    coverageResults?: AggregatedCoverageResults,
    options: ReportFormatOptions = {},
  ): string {
    const lines: string[] = [];

    // Main header
    lines.push("## Codecov Results 📊");
    lines.push("");

    // Add test results section
    if (testResults) {
      this.addTestResultsSection(lines, testResults);
    }

    // Add coverage section
    if (coverageResults) {
      this.addCoverageSection(lines, coverageResults, options);
    }

    // Footer
    lines.push("---");
    lines.push(
      "*Generated by [Codecov Action](https://github.com/getsentry/coverage-action)*",
    );

    return lines.join("\n");
  }

  /**
   * Add test results section to the report
   */
  private addTestResultsSection(
    lines: string[],
    results: AggregatedTestResults,
  ): void {
    // Summary line with emoji indicators
    const passEmoji = results.passedTests > 0 ? "✅" : "";
    const failEmoji = results.failedTests > 0 ? "❌" : "";
    const skipEmoji = results.skippedTests > 0 ? "⏭️" : "";

    const summaryParts: string[] = [];

    if (passEmoji) {
      summaryParts.push(`${passEmoji} **${results.passedTests} passed**`);
    }
    if (failEmoji) {
      summaryParts.push(`${failEmoji} **${results.failedTests} failed**`);
    }
    if (skipEmoji) {
      summaryParts.push(`${skipEmoji} **${results.skippedTests} skipped**`);
    }

    // Add total and pass rate
    summaryParts.push(`**Total: ${results.totalTests}**`);
    summaryParts.push(`**Pass Rate: ${results.passRate}%**`);
    summaryParts.push(
      `**Execution Time: ${this.formatTime(results.totalTime)}**`,
    );

    lines.push(summaryParts.join(" | "));
    lines.push("");

    // Add comparison section if available
    if (results.comparison) {
      this.addComparisonSection(lines, results.comparison);
    }

    // Show failed tests if any
    if (results.failedTests > 0 && results.failedTestCases.length > 0) {
      lines.push("### ❌ Failed Tests");
      lines.push("");

      for (const { suiteName, testCase } of results.failedTestCases) {
        // Test header
        lines.push(`#### \`${testCase.name}\``);
        lines.push(`**File:** \`${testCase.classname}\``);

        if (suiteName && suiteName !== testCase.classname) {
          lines.push(`**Suite:** \`${suiteName}\``);
        }

        if (testCase.failure) {
          lines.push(`**Error:** ${testCase.failure.message}`);
          lines.push("");

          // Stack trace in collapsible details
          if (testCase.failure.content) {
            lines.push("<details>");
            lines.push("<summary>Stack Trace</summary>");
            lines.push("");
            lines.push("```");
            lines.push(testCase.failure.content.trim());
            lines.push("```");
            lines.push("");
            lines.push("</details>");
            lines.push("");
          }
        }
      }
    } else if (results.failedTests === 0) {
      // Success message
      lines.push("All tests are passing successfully.");
      lines.push("");
    }

    lines.push("");
  }

  /**
   * Add coverage section to the report (Codecov-style format with icons)
   */
  private addCoverageSection(
    lines: string[],
    results: AggregatedCoverageResults,
    options: ReportFormatOptions,
  ): void {
    const patchTarget = options.patchTarget ?? 80;
    const patchBreakdown = options.patchFileBreakdown;

    if (results.patchCoverageRate !== undefined) {
      const patchRate = results.patchCoverageRate.toFixed(2);
      const patchEmoji =
        results.patchCoverageRate >= patchTarget ? ":white_check_mark:" : ":x:";
      const coveredLines =
        patchBreakdown?.reduce(
          (total, file) => total + file.coveredLines.length,
          0,
        ) ?? 0;
      const totalLines =
        patchBreakdown?.reduce(
          (total, file) =>
            total + file.coveredLines.length + file.missedLines.length,
          0,
        ) ?? 0;
      const patchDetails =
        totalLines > 0
          ? ` (${coveredLines} of ${totalLines} changed executable lines covered; target ${patchTarget}%).`
          : ` (no changed executable lines found; target ${patchTarget}%).`;
      lines.push(
        `${patchEmoji} Patch coverage is **${patchRate}%**${patchDetails}`,
      );
    } else {
      lines.push(
        ":information_source: Patch coverage was not calculated for this run.",
      );
    }

    let projectMessage = `Project statement coverage is **${results.lineRate.toFixed(2)}%**`;
    if (results.comparison) {
      const delta = results.comparison.deltaLineRate;
      const baseRef = results.comparison.baseCommit
        ? `\`${results.comparison.baseCommit.substring(0, 7)}\``
        : "base";
      const headRef = results.comparison.headCommit
        ? `\`${results.comparison.headCommit.substring(0, 7)}\``
        : "head";
      const change =
        delta === 0
          ? `unchanged from base (${baseRef}) to head (${headRef})`
          : `${delta > 0 ? "up" : "down"} ${Math.abs(delta).toFixed(2)} percentage points from base (${baseRef}) to head (${headRef})`;
      projectMessage += ` (${change})`;
    }
    lines.push(`${projectMessage}.`);
    lines.push("");

    const filesMode = options.filesMode || "changed";

    // When patch file breakdown is available (PR context), show every file
    // with measured changed executable lines so the patch summary is auditable.
    if (patchBreakdown && patchBreakdown.length > 0 && filesMode !== "none") {
      const patchFiles = [...patchBreakdown].sort(
        (a, b) =>
          b.missedLines.length +
          b.partialLines.length -
          (a.missedLines.length + a.partialLines.length),
      );

      lines.push("<details>");
      lines.push(
        `<summary>Changed files with executable lines (${patchFiles.length})</summary>`,
      );
      lines.push("");
      lines.push("| File | Patch coverage | Changed executable lines |");
      lines.push("|------|----------------|--------------------------|");

      for (const file of patchFiles) {
        const filePath = this.normalizeFilePath(file.path);
        const fileCell = this.formatFileCell(filePath, options.githubContext);
        const coveredCount = file.coveredLines.length;
        const missedCount = file.missedLines.length;
        const totalCount = coveredCount + missedCount;
        const lineDetails = [`${coveredCount}/${totalCount} covered`];

        if (missedCount > 0) {
          lineDetails.push(`missed: ${file.missedLines.join(", ")}`);
        }
        if (file.partialLines.length > 0) {
          lineDetails.push(`partial branches: ${file.partialLines.join(", ")}`);
        }

        lines.push(
          `| ${fileCell} | ${file.percentage.toFixed(2)}% | ${lineDetails.join("; ")} |`,
        );
      }
      lines.push("");
      lines.push("</details>");
      lines.push("");
    } else if (filesMode !== "none") {
      // Fallback: no patch breakdown available (push events / non-PR context)
      // Show project-wide missing lines as before.
      const filesWithMissing = this.getFilesWithMissingLines(results, options);

      if (filesWithMissing.length > 0) {
        lines.push("<details>");
        lines.push(
          `<summary>Files with missing lines (${filesWithMissing.length})</summary>`,
        );
        lines.push("");
        lines.push("| File | Coverage % | Lines |");
        lines.push("|------|------------|-------|");

        for (const file of filesWithMissing) {
          const filePath = this.normalizeFilePath(file.path);
          // Don't generate links for project-wide paths since they may be
          // absolute (from coverage parsers) and won't produce valid GitHub
          // diff anchors. Links are only reliable for patch breakdown paths
          // which come directly from the git diff.
          const fileCell = this.formatFileCell(filePath);
          const missingCount = file.missingLines?.length || 0;
          const partialCount = file.partialLines?.length || 0;

          let linesText = "";
          if (missingCount > 0 && partialCount > 0) {
            linesText = `:warning: ${missingCount} Missing and ${partialCount} partials`;
          } else if (missingCount > 0) {
            linesText = `:warning: ${missingCount} Missing`;
          } else if (partialCount > 0) {
            linesText = `:warning: ${partialCount} partials`;
          }

          lines.push(
            `| ${fileCell} | ${file.lineRate.toFixed(2)}% | ${linesText} |`,
          );
        }

        lines.push("");
        lines.push("</details>");
        lines.push("");
      }
    }

    // Coverage diff (collapsible)
    if (results.comparison) {
      this.addDetailedCoverageDiff(lines, results);
    }

    // Flags section (collapsible)
    if (results.flags && results.flags.length > 0) {
      this.addFlagsSection(lines, results);
    }
  }

  private getFilesWithMissingLines(
    results: AggregatedCoverageResults,
    options: ReportFormatOptions,
  ) {
    const allFilesWithMissing = results.files
      .filter(
        (f) =>
          (f.missingLines?.length || 0) > 0 ||
          (f.partialLines?.length || 0) > 0,
      )
      .sort((a, b) => {
        const aMissing =
          (a.missingLines?.length || 0) + (a.partialLines?.length || 0);
        const bMissing =
          (b.missingLines?.length || 0) + (b.partialLines?.length || 0);
        return bMissing - aMissing;
      });

    const filesMode = options.filesMode || "changed";
    if (filesMode !== "changed") {
      return allFilesWithMissing;
    }

    const changedFiles = options.changedFiles || [];
    if (changedFiles.length === 0) {
      return [];
    }

    const normalizedChangedFiles = changedFiles.map((filePath) =>
      this.normalizeFilePath(filePath),
    );
    const changedFilesSet = new Set(normalizedChangedFiles);

    return allFilesWithMissing.filter((file) =>
      this.matchesChangedFile(
        this.normalizeFilePath(file.path),
        normalizedChangedFiles,
        changedFilesSet,
      ),
    );
  }

  private normalizeFilePath(filePath: string): string {
    return filePath.replace(/\\/g, "/").replace(/^\.?\//, "");
  }

  private matchesChangedFile(
    normalizedCoveragePath: string,
    normalizedChangedFiles: string[],
    changedFilesSet: Set<string>,
  ): boolean {
    if (changedFilesSet.has(normalizedCoveragePath)) {
      return true;
    }

    // Coverage parsers can emit absolute paths while PR diffs are repo-relative,
    // or vice versa. Check suffix matching in both directions.
    return normalizedChangedFiles.some(
      (changedPath) =>
        normalizedCoveragePath.endsWith(`/${changedPath}`) ||
        changedPath.endsWith(`/${normalizedCoveragePath}`),
    );
  }

  /**
   * Add detailed coverage diff in diff code block format (collapsible)
   */
  private addDetailedCoverageDiff(
    lines: string[],
    results: AggregatedCoverageResults,
  ): void {
    const comparison = results.comparison;
    if (!comparison) return;

    const baseBranch = comparison.baseBranch || "main";
    const prLabel = "#PR";

    lines.push("<details>");
    lines.push("<summary>Coverage diff</summary>");
    lines.push("");
    lines.push("```diff");

    // Header
    lines.push("@@            Coverage Diff             @@");
    lines.push(
      `##    ${this.padCol(baseBranch, 10)}${this.padCol(
        prLabel,
        10,
      )}${this.padCol("+/-", 10)}##`,
    );
    lines.push("==========================================");

    // Coverage line (green if improved)
    const baseCoverage = `${(
      results.lineRate - comparison.deltaLineRate
    ).toFixed(2)}%`;
    const currentCoverage = `${results.lineRate.toFixed(2)}%`;
    const coverageDelta = `${this.formatDeltaSimple(
      comparison.deltaLineRate,
    )}%`;
    const coveragePrefix =
      comparison.deltaLineRate > 0
        ? "+"
        : comparison.deltaLineRate < 0
          ? "-"
          : " ";
    lines.push(
      `${coveragePrefix} Coverage${this.padCol(baseCoverage, 10)}${this.padCol(
        currentCoverage,
        10,
      )}${this.padCol(coverageDelta, 10)}`,
    );

    lines.push("==========================================");

    // Neutral metrics (Files, tracked lines, Branches)
    const baseFiles = String(comparison.baseFiles || 0);
    const currentFiles = String(comparison.currentFiles || 0);
    const deltaFiles = this.formatDeltaSimple(comparison.deltaFiles || 0);
    lines.push(
      `  Files   ${this.padCol(baseFiles, 10)}${this.padCol(
        currentFiles,
        10,
      )}${this.padCol(deltaFiles, 10)}`,
    );

    const baseLines = String(comparison.baseLines || 0);
    const currentLines = String(comparison.currentLines || 0);
    const deltaLines = this.formatDeltaSimple(comparison.deltaLines || 0);
    lines.push(
      `  Tracked lines${this.padCol(baseLines, 10)}${this.padCol(
        currentLines,
        10,
      )}${this.padCol(deltaLines, 10)}`,
    );

    const baseBranches = String(comparison.baseBranches || 0);
    const currentBranches = String(comparison.currentBranches || 0);
    const deltaBranches = this.formatDeltaSimple(comparison.deltaBranches || 0);
    lines.push(
      `  Branches${this.padCol(baseBranches, 10)}${this.padCol(
        currentBranches,
        10,
      )}${this.padCol(deltaBranches, 10)}`,
    );

    lines.push("==========================================");

    // Hits (green when increased, neutral when unchanged)
    const baseHits = String(comparison.baseHits || 0);
    const currentHits = String(comparison.currentHits || 0);
    const deltaHits = this.formatDeltaSimple(comparison.deltaHits || 0);
    const hitsPrefix =
      comparison.deltaHits && comparison.deltaHits > 0
        ? "+"
        : comparison.deltaHits && comparison.deltaHits < 0
          ? "-"
          : " ";
    lines.push(
      `${hitsPrefix} Hits    ${this.padCol(baseHits, 10)}${this.padCol(
        currentHits,
        10,
      )}${this.padCol(deltaHits, 10)}`,
    );

    // Misses (green when reduced, red when increased)
    const baseMisses = String(comparison.baseMisses || 0);
    const currentMisses = String(comparison.currentMisses || 0);
    const deltaMisses = this.formatDeltaSimple(comparison.deltaMisses || 0);
    const missesPrefix =
      comparison.deltaMisses && comparison.deltaMisses < 0
        ? "+"
        : comparison.deltaMisses && comparison.deltaMisses > 0
          ? "-"
          : " ";
    lines.push(
      `${missesPrefix} Misses  ${this.padCol(baseMisses, 10)}${this.padCol(
        currentMisses,
        10,
      )}${this.padCol(deltaMisses, 10)}`,
    );

    // Partials (green when reduced, red when increased)
    const basePartials = String(comparison.basePartials || 0);
    const currentPartials = String(comparison.currentPartials || 0);
    const deltaPartials = this.formatDeltaSimple(comparison.deltaPartials || 0);
    const partialsPrefix =
      comparison.deltaPartials && comparison.deltaPartials < 0
        ? "+"
        : comparison.deltaPartials && comparison.deltaPartials > 0
          ? "-"
          : " ";
    lines.push(
      `${partialsPrefix} Partials${this.padCol(basePartials, 10)}${this.padCol(
        currentPartials,
        10,
      )}${this.padCol(deltaPartials, 10)}`,
    );

    lines.push("```");
    lines.push("");
    lines.push("</details>");
    lines.push("");
  }

  /**
   * Pad a column value for alignment
   */
  private padCol(value: string, width: number): string {
    return value.padStart(width);
  }

  /**
   * Add flags section (collapsible)
   */
  private addFlagsSection(
    lines: string[],
    results: AggregatedCoverageResults,
  ): void {
    if (!results.flags || results.flags.length === 0) return;

    lines.push("<details>");
    lines.push(`<summary>Flags (${results.flags.length})</summary>`);
    lines.push("");

    for (const flag of results.flags) {
      const coverageChange = results.comparison
        ? ` (${this.formatCoverageDelta(results.comparison.deltaLineRate)}%)`
        : "";
      lines.push(`- \`${flag}\`: ${results.lineRate}%${coverageChange}`);
    }
    lines.push("");
    lines.push("</details>");
    lines.push("");
  }

  /**
   * Format a file path as a markdown table cell, optionally linked to the
   * GitHub PR diff view when context is available.
   */
  private formatFileCell(filePath: string, context?: GitHubContext): string {
    if (context) {
      const url = this.buildPrDiffUrl(filePath, context);
      return `[${filePath}](${url})`;
    }
    return `\`${filePath}\``;
  }

  /**
   * Build a URL to a file in the GitHub PR diff view.
   * GitHub anchors each file diff with #diff-{sha256hex(filepath)}.
   */
  private buildPrDiffUrl(filePath: string, context: GitHubContext): string {
    const hash = createHash("sha256").update(filePath).digest("hex");
    return `${context.serverUrl}/${context.owner}/${context.repo}/pull/${context.prNumber}/files#diff-${hash}`;
  }

  /**
   * Format delta value with sign only (no emoji)
   */
  private formatDeltaSimple(delta: number): string {
    if (delta === 0) return "—";
    const sign = delta > 0 ? "+" : "";
    return `${sign}${delta}`;
  }

  /**
   * Add comparison section to the report
   */
  private addComparisonSection(
    lines: string[],
    comparison: TestComparison,
  ): void {
    lines.push("### 📊 Comparison with Base Branch");
    lines.push("");

    // Summary table
    lines.push("| Metric | Change |");
    lines.push("|--------|--------|");
    lines.push(`| Total Tests | ${this.formatDelta(comparison.deltaTotal)} |`);
    lines.push(
      `| Passed Tests | ${this.formatDelta(comparison.deltaPassed)} |`,
    );
    lines.push(
      `| Failed Tests | ${this.formatDelta(comparison.deltaFailed)} |`,
    );
    lines.push(
      `| Skipped Tests | ${this.formatDelta(comparison.deltaSkipped)} |`,
    );
    lines.push("");

    // Tests broken (regressions)
    if (comparison.testsBroken.length > 0) {
      lines.push(`#### 🔴 Tests Broken (${comparison.testsBroken.length})`);
      lines.push("");
      lines.push("<details>");
      lines.push("<summary>View broken tests</summary>");
      lines.push("");
      for (const testChange of comparison.testsBroken) {
        lines.push(`- \`${testChange.identifier.testName}\``);
        lines.push(`  - **File:** \`${testChange.identifier.classname}\``);
        if (testChange.testCase.failure) {
          lines.push(`  - **Error:** ${testChange.testCase.failure.message}`);
        }
      }
      lines.push("");
      lines.push("</details>");
      lines.push("");
    }

    // Tests fixed (improvements)
    if (comparison.testsFixed.length > 0) {
      lines.push(`#### 🟢 Tests Fixed (${comparison.testsFixed.length})`);
      lines.push("");
      lines.push("<details>");
      lines.push("<summary>View fixed tests</summary>");
      lines.push("");
      for (const testChange of comparison.testsFixed) {
        lines.push(`- \`${testChange.identifier.testName}\``);
        lines.push(`  - **File:** \`${testChange.identifier.classname}\``);
      }
      lines.push("");
      lines.push("</details>");
      lines.push("");
    }

    // Tests added
    if (comparison.testsAdded.length > 0) {
      lines.push(`#### ➕ New Tests (${comparison.testsAdded.length})`);
      lines.push("");
      lines.push("<details>");
      lines.push("<summary>View new tests</summary>");
      lines.push("");
      for (const testChange of comparison.testsAdded) {
        lines.push(`- \`${testChange.identifier.testName}\``);
        lines.push(`  - **File:** \`${testChange.identifier.classname}\``);
        if (testChange.testCase.failure) {
          lines.push(`  - **Status:** ❌ Failing`);
        } else {
          lines.push(`  - **Status:** ✅ Passing`);
        }
      }
      lines.push("");
      lines.push("</details>");
      lines.push("");
    }

    // Tests removed
    if (comparison.testsRemoved.length > 0) {
      lines.push(`#### ➖ Removed Tests (${comparison.testsRemoved.length})`);
      lines.push("");
      lines.push("<details>");
      lines.push("<summary>View removed tests</summary>");
      lines.push("");
      for (const testChange of comparison.testsRemoved) {
        lines.push(`- \`${testChange.identifier.testName}\``);
        lines.push(`  - **File:** \`${testChange.identifier.classname}\``);
      }
      lines.push("");
      lines.push("</details>");
      lines.push("");
    }

    // Summary message
    if (
      comparison.testsBroken.length === 0 &&
      comparison.testsFixed.length === 0 &&
      comparison.testsAdded.length === 0 &&
      comparison.testsRemoved.length === 0 &&
      comparison.deltaTotal === 0
    ) {
      lines.push("✨ Test counts unchanged from base.");
      lines.push("");
    }
  }

  /**
   * Format a delta value with appropriate sign and emoji
   */
  private formatDelta(delta: number): string {
    if (delta === 0) {
      return "—";
    }
    const sign = delta > 0 ? "+" : "";
    const emoji = delta > 0 ? "📈" : "📉";
    return `${emoji} ${sign}${delta}`;
  }

  /**
   * Format a coverage delta value with appropriate sign
   */
  private formatCoverageDelta(delta: number): string {
    if (delta === 0) {
      return "±0.00";
    }
    const sign = delta > 0 ? "+" : "";
    return `${sign}${delta.toFixed(2)}`;
  }

  /**
   * Format execution time in a human-readable way
   */
  private formatTime(seconds: number): string {
    if (seconds < 1) {
      return `${Math.round(seconds * 1000)}ms`;
    }
    if (seconds < 60) {
      return `${seconds.toFixed(2)}s`;
    }
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = seconds % 60;
    return `${minutes}m ${remainingSeconds.toFixed(0)}s`;
  }

  /**
   * Generate a unique identifier for the comment
   * This helps identify comments created by this action
   */
  static getCommentIdentifier(key?: string): string {
    return key
      ? `<!-- codecov-action-results:${key} -->`
      : "<!-- codecov-action-results -->";
  }

  /**
   * Legacy identifier for backward compatibility
   */
  static getLegacyCommentIdentifier(): string {
    return "<!-- codecov-action-test-results -->";
  }

  /**
   * Add identifier to comment body
   */
  addIdentifier(comment: string): string {
    return `${ReportFormatter.getCommentIdentifier()}\n${comment}`;
  }
}
