name: Build & Test

on:
  pull_request:
  push:
    branches:
      - main
      - "release/**"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Required for posting/updating PR comments
      statuses: write # Required for reporting commit statuses

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Action
        run: pnpm run build

      - name: Run tests
        run: pnpm test

      - name: Test Analysis
        id: analysis
        uses: ./ # TODO: later remove this with the public address
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: npm pack

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: action-package
          path: "*.tgz"

  build_website:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build website
        working-directory: website
        run: pnpm run build

      - name: Check GitHub Pages routes
        working-directory: website
        run: pnpm run test:build

      - name: Package for gh-pages
        run: cd website/dist && zip -r ../../gh-pages.zip .

      - name: Upload gh-pages artifact
        uses: actions/upload-artifact@v7
        with:
          name: gh-pages
          path: gh-pages.zip
